name: Fetch Secrets from Key Vault

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      KEYVAULT_NAME:
        required: true
    outputs:
      SONAR_TOKEN:
        description: "Sonar Token"
        value: ${{ jobs.get-secrets.outputs.sonar }}
      TWISTLOCK_PASSWORD:
        description: "Twistlock Password"
        value: ${{ jobs.get-secrets.outputs.twistlock }}

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    outputs:
      sonar: ${{ steps.kv.outputs.sonar }}
      twistlock: ${{ steps.kv.outputs.twistlock }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get secrets from Key Vault
        id: kv
        uses: azure/secrets@v1
        with:
          keyvault: ${{ secrets.KEYVAULT_NAME }}
          secrets: |
            sonar
            twistlock
