name: Deploy NGINX Ingress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        run: az aks get-credentials --resource-group <resource-group> --name <aks-cluster> --overwrite-existing

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install nginx-ingress ./nginx-ingress             --namespace nonprod --create-namespace
