apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: {{ .Values.controller.service.type }}
  selector:
    app: nginx-ingress
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: {{ .Values.controller.service.nodePorts.http }}
    - name: https
      port: 443
      targetPort: 443
      nodePort: {{ .Values.controller.service.nodePorts.https }}
