{{- if .Values.controller.ssl.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controller.ssl.secretName }}
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>
{{- end }}
